// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ahmadammarm/sommerce-mini-project/internal/alamat"
	"github.com/ahmadammarm/sommerce-mini-project/internal/category"
	"github.com/ahmadammarm/sommerce-mini-project/internal/produk"
	"github.com/ahmadammarm/sommerce-mini-project/internal/router"
	"github.com/ahmadammarm/sommerce-mini-project/internal/toko"
	"github.com/ahmadammarm/sommerce-mini-project/internal/transaction"
	"github.com/ahmadammarm/sommerce-mini-project/internal/user"
	"github.com/ahmadammarm/sommerce-mini-project/pkg/config"
	"github.com/ahmadammarm/sommerce-mini-project/pkg/emsifa"
	"github.com/ahmadammarm/sommerce-mini-project/pkg/uid"
	"github.com/gofiber/fiber/v2"
)

// Injectors from wire.go:

func InitializeApp() (*fiber.App, error) {
	db, err := config.NewDatabase()
	if err != nil {
		return nil, err
	}
	userRepository := user.NewUserRepository(db)
	tokoRepository := toko.NewTokoRepository(db)
	wilayahProvider := emsifa.NewEmsifaClient()
	idGenerator := uid.NewIDGenerator()
	validate := config.NewValidator()
	userService := user.NewUserService(userRepository, tokoRepository, wilayahProvider, idGenerator, validate)
	userHandler := user.NewUserHandler(userService)
	tokoService := toko.NewTokoService(tokoRepository, validate)
	tokoHandler := toko.NewTokoHandler(tokoService)
	alamatRepository := alamat.NewAlamatRepository(db)
	alamatService := alamat.NewAlamatService(alamatRepository, wilayahProvider, idGenerator, validate)
	alamatHandler := alamat.NewAlamatHandler(alamatService)
	categoryRepository := category.NewCategoryRepository(db)
	categoryService := category.NewCategoryService(categoryRepository, idGenerator, validate)
	categoryHandler := category.NewCategoryHandler(categoryService)
	produkRepository := produk.NewProdukRepository(db)
	produkService := produk.NewProdukService(produkRepository, tokoRepository, idGenerator, validate)
	produkHandler := produk.NewProdukHandler(produkService)
	transactionRepository := transaction.NewTransactionRepository(db)
	transactionService := transaction.NewTransactionService(transactionRepository, produkRepository, alamatRepository, idGenerator, validate)
	transactionHandler := transaction.NewTransactionHandler(transactionService)
	app := router.NewRouter(userHandler, tokoHandler, alamatHandler, categoryHandler, produkHandler, transactionHandler)
	return app, nil
}
